name: "Prepare empty runner"
description: "scale set is an empty runner with nothing installed"

inputs:
  cache-read-only:
    description: 'if we should save caches or not'
    required: false
    default: 'true'
  cache-encryption-key:
    description: 'configuration cache key'
    required: true
  setup-java-21:
    description: 'Setup java'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup java 21
      if: ${{ inputs.setup-java-21 == 'true' }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ inputs.cache-read-only }}
        cache-encryption-key: ${{ inputs.cache-key }}
        cache-cleanup: on-success

    - name: Setup Android SDK
      uses: premex-ab/setup-android@v4
      with:
        cmdline-tools-version: 12266719